---
Title: Test

lang: de
---

In Front des schon seit Kurfürst Georg Wilhelm von der Familie von Briest bewohnten Herrenhauses zu Hohen-Cremmen fiel heller Sonnenschein auf die mittagsstille Dorfstraße, während nach der Park- und Gartenseite hin ein rechtwinklig angebauter Seitenflügel einen breiten Schatten erst auf einen weiß und grün quadrierten Fliesengang und dann über diesen hinaus auf ein großes, in seiner Mitte mit einer Sonnenuhr und an seinem Rande mit Canna indica und Rhabarberstauden besetzten Rondell warf. Einige zwanzig Schritte weiter, in Richtung und Lage genau dem Seitenflügel entsprechend, lief eine ganz in kleinblättrigem Efeu stehende, nur an einer Stelle von einer kleinen weißgestrichenen Eisentür unterbrochene Kirchhofsmauer, hinter der der Hohen-Cremmener Schindelturm mit seinem blitzenden, weil neuerdings erst wieder vergoldeten Wetterhahn aufragte. Fronthaus, Seitenflügel und Kirchhofsmauer bildeten ein einen kleinen Ziergarten umschließendes Hufeisen, an dessen offener Seite man eines Teiches mit Wassersteg und angekettetem Boot und dicht daneben einer Schaukel gewahr wurde, deren horizontal gelegtes Brett zu Häupten und Füßen an je zwei Stricken hing – die Pfosten der Balkenlage schon etwas schief stehend. Zwischen Teich und Rondell aber und die Schaukel halb versteckend standen ein paar mächtige alte Platanen.

Auch die Front des Herrenhauses – eine mit Aloekübeln und ein paar Gartenstühlen besetzte Rampe – gewährte bei bewölktem Himmel einen angenehmen und zugleich allerlei Zerstreuung bietenden Aufenthalt; an Tagen aber, wo die Sonne niederbrannte, wurde die Gartenseite ganz entschieden bevorzugt, besonders von Frau und Tochter des Hauses, die denn auch heute wieder auf dem im vollen Schatten liegenden Fliesengange saßen, in ihrem Rücken ein paar offene, von wildem Wein umrankte Fenster, neben sich eine vorspringende kleine Treppe, deren vier Steinstufen vom Garten aus in das Hochparterre des Seitenflügels hinaufführten. Beide, Mutter und Tochter, waren fleißig bei der Arbeit, die der Herstellung eines aus Einzelquadraten zusammenzusetzenden Altarteppichs galt; ungezählte Wollsträhnen und Seidendocken lagen auf einem großen, runden Tisch bunt durcheinander, dazwischen, noch vom Lunch her, ein paar Dessertteller und eine mit großen schönen Stachelbeeren gefüllte Majolikaschale. Rasch und sicher ging die Wollnadel der Damen hin und her, aber während die Mutter kein Auge von der Arbeit ließ, legte die Tochter, die den Rufnamen Effi führte, von Zeit zu Zeit die Nadel nieder und erhob sich, um unter allerlei kunstgerechten Beugungen und Streckungen den ganzen Kursus der Heil- und Zimmergymnastik durchzumachen. Es war ersichtlich, daß sie sich diesen absichtlich ein wenig ins Komische gezogenen Übungen mit ganz besonderer Liebe hingab, und wenn sie dann so dastand und, langsam die Arme hebend, die Handflächen hoch über dem Kopf zusammenlegte, so sah auch wohl die Mama von ihrer Handarbeit auf, aber immer nur flüchtig und verstohlen, weil sie nicht zeigen wollte, wie entzückend sie ihr eigenes Kind finde, zu welcher Regung mütterlichen Stolzes sie voll berechtigt war. Effi trug ein blau und weiß gestreiftes, halb kittelartiges Leinwandkleid, dem erst ein fest zusammengezogener, bronzefarbener Ledergürtel die Taille gab; der Hals war frei, und über Schulter und Nacken fiel ein breiter Matrosenkragen. In allem, was sie tat, paarten sich Übermut und Grazie, während ihre lachenden braunen Augen eine große, natürliche Klugheit und viel Lebenslust und Herzensgüte verrieten. Man nannte sie die »Kleine«, was sie sich nur gefallen lassen mußte, weil die schöne, schlanke Mama noch um eine Handbreit höher war.
